server:
  port: ${PORT:8761}
application:
  name: ^project.artifactId^
  description: ^project.name^
  version: ^project.version^
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/